Repository gravwell/gravwell, pull requests merged in 2022-11, with the labels that each got.

#536 Make sure we use concurrency-safe random sources for auth challenges.
  ingest/auth.go
  ingest/utils.go
Labels: bug

#537 using a gravwell maintained repo for the o365 lib
  go.mod
  go.sum
  ingesters/O365Ingester/config.go
  ingesters/O365Ingester/main.go
Labels: enhancement

#538 Dev->master
  client/resources.go
  client/types/api.go
  client/types/users.go
  filewatch/filters.go
  filewatch/reader.go
  filewatch/reader_linux.go
  filewatch/reader_windows.go
  go.mod
  go.sum
  ingest/auth.go
  ingest/processors/corelight.go
  ingest/utils.go
  ingesters/O365Ingester/config.go
  ingesters/O365Ingester/main.go
  ingesters/fileFollow/ConfigurationDlg.wxs
  ingesters/fileFollow/WixUI_HK.wxs
  ingesters/fileFollow/createConfigFile.vbs
  ingesters/fileFollow/customActions.vbs
  ingesters/fileFollow/en-us.wxl
  ingesters/fileFollow/main_windows.go
  ingesters/fileFollow/processing_windows.go
  ingesters/fileFollow/product.wxs
  ingesters/netflow/netflow_capture.conf
  ingesters/version/version.go
  ingesters/winevents/WixUI_HK.wxs
  ingesters/winevents/en-us.wxl
  winevent/bookmark.go
  winevent/config.go
  winevent/winevent.go
  winevent/wineventlog/syscall_windows.go
  winevent/wineventlog/zsyscall_windows.go
Labels: task

#540 removing the cpu and memory profiling of ingesters
  ingesters/KinesisIngester/main.go
  ingesters/PacketFleet/main.go
  ingesters/SimpleRelay/main.go
  ingesters/collectd/main.go
  ingesters/kafka_consumer/main.go
  ingesters/netflow/main.go
  ingesters/networkLog/main.go
  ingesters/sqsIngester/main.go
Labels: task

#542 running gofmt
  chancacher/chancacher.go
  client/admin.go
  client/client.go
  client/info.go
  client/types/abac.go
  client/types/api.go
  client/types/chart.go
  client/types/kits/reader.go
  client/types/search.go
  client/types/users.go
  client/websocketRouter/client.go
  client/websocketRouter/router_test.go
  client/websocketRouter/server.go
  generators/gravwellGenerator/binarygen.go
  ingest/config/config.go
  ingest/entryConfBuffer.go
  ingest/entryReader.go
  ingest/entryWriter.go
  ingest/entry_buff.go
  ingest/log/logging.go
  ingest/muxer.go
  ingest/processors/cisco_ise_data_test.go
  ingest/simple.go
  ingesters/AzureEventHubs/main.go
  ingesters/PacketFleet/main.go
  ingesters/kafka_consumer/consumer.go
  ingesters/massFile/processing.go
  ingesters/networkLog/main.go
  ingesters/utils/parse.go
  ingesters/winevents/processing.go
  manager/config.go
  netflow/nfv5.go
  timegrinder/processors.go
  winevent/wineventlog/query.go
  winevent/wineventlog/zsyscall_windows.go
Labels: task

#544 Bringing in the S3 ingester
  go.mod
  go.sum
  ingesters/base/base.go
  ingesters/s3Ingster/.gitignore
  ingesters/s3Ingster/bucket.go
  ingesters/s3Ingster/config.go
  ingesters/s3Ingster/main.go
  ingesters/s3Ingster/manager.go
  ingesters/s3Ingster/s3.conf
  ingesters/s3Ingster/utils.go
Labels: feature

#547 fixing default config and missing state store loc param
  ingesters/s3Ingester/config.go
  ingesters/s3Ingester/s3.conf
Labels: enhancement

#548 upping max line size becuase cloud trail can throw some massive events
  ingesters/s3Ingester/bucket.go
  ingesters/s3Ingester/config.go
  ingesters/s3Ingester/main.go
Labels: feature

#549 Master -> Dev
  go.mod
  go.sum
  ingesters/base/base.go
  ingesters/s3Ingester/.gitignore
  ingesters/s3Ingester/bucket.go
  ingesters/s3Ingester/config.go
  ingesters/s3Ingester/main.go
  ingesters/s3Ingester/manager.go
  ingesters/s3Ingester/s3.conf
  ingesters/s3Ingester/utils.go
Labels: task

#552 fixing up bucket ARN/URL/Name logic
  ingesters/s3Ingester/.gitignore
  ingesters/s3Ingester/bucket.go
Labels: enhancement

#554 changing Bucket-URL to Bucket-ARN to clarify,
  ingesters/s3Ingester/bucket.go
  ingesters/s3Ingester/s3.conf
Labels: enhancement

#557 adding json timestamp extraction preprocessor
  ingest/processors/jsontimeextract.go
  ingest/processors/jsontimeextract_test.go
  ingest/processors/processors.go
Labels: feature

#560 Backup timeout
  client/admin.go
Labels: enhancement

#561 fixing up client to pull tls config from existing client on backup
  client/admin.go
Labels: bug

#562 adding checks for errors on bad keys in configs
  go.mod
  go.sum
  ingest/config/loader_test.go
Labels: enhancement

#563 adding in some packages to the plugin system
  ingest/processors/jsontimeextract.go
  ingest/processors/plugin/packages.Scriggofile
  ingest/processors/plugin/packages.go
Labels: enhancement
